# theme: jekyll-theme-minimal
title: tukasa no hoehoe wiki
description: tukasa no page
url: https://tukasa.github.io/
baseurl: /hoehoe_practice
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"